/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MazeRankIndexRouteImport } from './routes/maze-rank/index'
import { Route as MazeRankLiveRankRouteImport } from './routes/maze-rank/live.$rank'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MazeRankIndexRoute = MazeRankIndexRouteImport.update({
  id: '/maze-rank/',
  path: '/maze-rank/',
  getParentRoute: () => rootRouteImport,
} as any)
const MazeRankLiveRankRoute = MazeRankLiveRankRouteImport.update({
  id: '/maze-rank/live/$rank',
  path: '/maze-rank/live/$rank',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maze-rank/': typeof MazeRankIndexRoute
  '/maze-rank/live/$rank': typeof MazeRankLiveRankRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maze-rank': typeof MazeRankIndexRoute
  '/maze-rank/live/$rank': typeof MazeRankLiveRankRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maze-rank/': typeof MazeRankIndexRoute
  '/maze-rank/live/$rank': typeof MazeRankLiveRankRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/maze-rank/' | '/maze-rank/live/$rank'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/maze-rank' | '/maze-rank/live/$rank'
  id: '__root__' | '/' | '/maze-rank/' | '/maze-rank/live/$rank'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MazeRankIndexRoute: typeof MazeRankIndexRoute
  MazeRankLiveRankRoute: typeof MazeRankLiveRankRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maze-rank/': {
      id: '/maze-rank/'
      path: '/maze-rank'
      fullPath: '/maze-rank/'
      preLoaderRoute: typeof MazeRankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maze-rank/live/$rank': {
      id: '/maze-rank/live/$rank'
      path: '/maze-rank/live/$rank'
      fullPath: '/maze-rank/live/$rank'
      preLoaderRoute: typeof MazeRankLiveRankRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MazeRankIndexRoute: MazeRankIndexRoute,
  MazeRankLiveRankRoute: MazeRankLiveRankRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
